# ─────────────────────────────────────────────────────────────────────────────
# Dantzig-Wolfe Column Generation  (single- and multi-column)
# ─────────────────────────────────────────────────────────────────────────────
#

# ── Helpers ───────────────────────────────────────────────────────────────────

"""
    _solve_cg_subproblems!(subproblems, λ, π, p, eps, pool_size)
        -> (new_p, new_c, neg_rc)

Solve all per-generator subproblems in parallel with current duals `λ`.

For each generator `g`:
  - minimises  `cost(p,u,v) − Σ_t λ_t * p_t`  (the Lagrangian relaxation)
  - computes reduced cost  `rc_g = h_g* − π_g`
  - if `rc_g < −eps`, appends the column `(p̂, ĉ)` to `new_p[g]` / `new_c[g]`
    and sets `neg_rc[g] = true`

When `pool_size > 1` Gurobi's solution pool is used; all pool solutions with
negative reduced cost are collected.

Returns:
- `new_p::Vector{Vector{Vector{Float64}}}` — new production profiles per generator
- `new_c::Vector{Vector{Float64}}`          — new column costs per generator
- `neg_rc::BitVector`                       — which generators produced a column
"""
function _solve_cg_subproblems!(subproblems, λ, π, p, eps, pool_size)
    T, NbGen = p.T, p.NbGen
    new_p = [Vector{Vector{Float64}}() for _ = 1:NbGen]
    new_c = [Vector{Float64}() for _ = 1:NbGen]
    neg_rc = falses(NbGen)

    Threads.@threads for gen = 1:NbGen
        sub = subproblems[gen]
        @objective(sub.model, Min, sub.VarCost - sum(λ[t] * sub.Varp[t] for t = 1:T))
        optimize!(sub.model)

        nsols = result_count(sub.model)
        for s = 1:max(nsols, 0)
            rc = (
                value(sub.VarCost; result = s) -
                sum(λ[t] * value(sub.Varp[t]; result = s) for t = 1:T) - π[gen]
            )
            if rc < -eps
                neg_rc[gen] = true
                push!(new_p[gen], [value(sub.Varp[t]; result = s) for t = 1:T])
                push!(new_c[gen], value(sub.VarCost; result = s))
            end
        end
    end

    return new_p, new_c, neg_rc
end

"""
    _add_columns!(rmp, balance, convex, z_vars, cols_p, cols_c, new_p, new_c)

Add new columns to the RMP in-place by appending JuMP variables and updating
the constraint matrix and objective coefficients.
"""
function _add_columns!(rmp, balance, convex, z_vars, cols_p, cols_c, new_p, new_c)
    T = length(balance)
    NbGen = length(z_vars)
    for gen = 1:NbGen
        for (p_col, c_col) in zip(new_p[gen], new_c[gen])
            z_new = @variable(rmp, lower_bound = 0)
            for t = 1:T
                set_normalized_coefficient(balance[t], z_new, p_col[t])
            end
            set_normalized_coefficient(convex[gen], z_new, 1.0)
            set_objective_coefficient(rmp, z_new, c_col)
            push!(z_vars[gen], z_new)
            push!(cols_p[gen], p_col)
            push!(cols_c[gen], c_col)
        end
    end
end

# ── Core Column Generation ────────────────────────────────────────────────────

"""
    ColumnGeneration(instance, initial_prices, stop::StoppingCriterion, eps;
                     pool_size=1, verbose=-1)

Dantzig-Wolfe column generation for the unit commitment problem.

The algorithm follows the Dantzig-Wolfe decomposition described in
Andrianesis et al. (2021).  The Restricted Master Program (RMP) is an LP
that maintains a convex combination of feasible per-generator schedules; new
schedules are generated by pricing subproblems solved as small MILPs.

## Iteration structure
1. Solve the RMP (LP). Extract duals `λ_t` (balance) and `π_g` (convexity).
2. For each generator `g`, solve:
     `min_{schedule} cost(schedule) − Σ_t λ_t p_t`
   Reduced cost: `rc_g = h_g* − π_g`.
3. If all `rc_g ≥ −eps`: **terminate** — `λ` are the convex-hull prices.
4. Otherwise add columns with `rc_g < −eps` to the RMP and repeat.

## Keyword arguments
- `pool_size` : solutions requested from Gurobi's pool per generator per
  iteration. `pool_size=1` (default) gives classic single-column CG;
  `pool_size=K` gives multi-column CG (Andrianesis et al., 2021).
- `verbose`   : print iteration info when `> 0`.

Works with any `StoppingCriterion`:
- `IterationLimit(n)` — at most `n` CG iterations.
- `TimeBudget(τ)`     — at most `τ` seconds (wall-clock).

## Initial columns
Each generator's subproblem is solved at `initial_prices` to produce the
first column(s) (warm start).  Passing `zeros(T)` gives a flat start where
each generator self-schedules at zero price (producing zero output).

## Returns
`(x_best, iterates, fun_iterates, time_vector)` where
- `x_best`       — final (optimal) price vector `λ`
- `iterates`     — sequence of price vectors `[initial_prices, λ^(1), …]`
- `fun_iterates` — RMP objective values (tightening lower bound on primal opt.)
- `time_vector`  — cumulative wall-clock time after each iteration
"""
function ColumnGeneration(
    instance,
    initial_prices,
    stop::StoppingCriterion,
    eps;
    pool_size::Int = 1,
    verbose::Int = -1,
)
    p = unpack_instance(instance)
    T, NbGen = p.T, p.NbGen
    M = p.LostLoad   # slack penalty (= LostLoad $/MWh)

    iterates = [copy(initial_prices)]
    fun_iterates = Float64[]
    time_vector = [0.0]

    # ── Build and cache per-generator subproblem models ────────────────────
    subproblems = [build_cg_subproblem(gen, p) for gen = 1:NbGen]
    if pool_size > 1
        for gen = 1:NbGen
            set_optimizer_attribute(subproblems[gen].model, "PoolSolutions", pool_size)
            set_optimizer_attribute(subproblems[gen].model, "PoolSearchMode", 2)
        end
    end

    # ── Generate initial columns from initial_prices (warm / flat start) ───
    # cols_p[g]: list of T-length production profiles for generator g
    # cols_c[g]: corresponding production costs (= RMP column cost ĉ_g^[n])
    cols_p = [Vector{Vector{Float64}}() for _ = 1:NbGen]
    cols_c = [Vector{Float64}() for _ = 1:NbGen]

    for gen = 1:NbGen
        sub = subproblems[gen]
        @objective(
            sub.model,
            Min,
            sub.VarCost - sum(initial_prices[t] * sub.Varp[t] for t = 1:T)
        )
        optimize!(sub.model)
        nsols = result_count(sub.model)
        if nsols == 0
            # Fallback: zero-production column (always feasible)
            push!(cols_p[gen], zeros(T))
            push!(cols_c[gen], 0.0)
        else
            for s = 1:nsols
                push!(cols_p[gen], [value(sub.Varp[t]; result = s) for t = 1:T])
                push!(cols_c[gen], value(sub.VarCost; result = s))
            end
        end
    end

    # ── Build initial RMP ──────────────────────────────────────────────────
    rmp = new_gurobi_model()

    # Slack variables s_t ≥ 0 for each time period (absorb unmet load)
    s_vars = @variable(rmp, [t = 1:T], lower_bound = 0)

    # z variables: one per column per generator
    z_vars = [Vector{JuMP.VariableRef}() for _ = 1:NbGen]
    for gen = 1:NbGen
        for _ in eachindex(cols_p[gen])
            push!(z_vars[gen], @variable(rmp, lower_bound = 0))
        end
    end

    # Balance constraints: Σ_{g,n} p̂_g^n_t · z_g^n + s_t = L_t  →  dual λ_t
    balance = @constraint(
        rmp,
        [t = 1:T],
        sum(
            sum(cols_p[gen][n][t] * z_vars[gen][n] for n in eachindex(z_vars[gen])) for
            gen = 1:NbGen
        ) + s_vars[t] == p.L[t]
    )

    # Convexity constraints: Σ_n z_g^n = 1 for each g  →  dual π_g
    convex = [
        @constraint(rmp, sum(z_vars[gen][n] for n in eachindex(z_vars[gen])) == 1) for
        gen = 1:NbGen
    ]

    # RMP objective: production costs + slack penalty
    @objective(
        rmp,
        Min,
        sum(
            sum(cols_c[gen][n] * z_vars[gen][n] for n in eachindex(z_vars[gen])) for
            gen = 1:NbGen
        ) + M * sum(s_vars)
    )

    # ── Main CG loop ───────────────────────────────────────────────────────
    iter = 1
    while should_continue(stop, iter, time_vector[end])
        n_cols = sum(length(z_vars[gen]) for gen = 1:NbGen)
        verbose > 0 &&
            @info "[CG: iter=$iter, cols=$n_cols, t=$(round(time_vector[end]; digits=2))s]"

        done = false
        it_time = @elapsed begin

            # ── 1. Solve RMP ─────────────────────────────────────────────
            optimize!(rmp)
            push!(fun_iterates, objective_value(rmp))

            # ── 2. Extract duals ─────────────────────────────────────────
            # Use `dual` (not `shadow_price`): in direct Gurobi LP models the
            # raw solver dual already carries the correct sign for the D-W
            # pricing formula  rc = h* − π.  `shadow_price` negates it.
            λ = [dual(balance[t]) for t = 1:T]
            π = [dual(convex[gen]) for gen = 1:NbGen]
            push!(iterates, copy(λ))

            # ── 3. Solve subproblems (parallel) ──────────────────────────
            new_p, new_c, neg_rc =
                _solve_cg_subproblems!(subproblems, λ, π, p, eps, pool_size)

            # ── 4. Termination check ─────────────────────────────────────
            if !any(neg_rc)
                verbose > 0 &&
                    @info "[CG: converged at iter=$iter (no negative reduced costs)]"
                done = true
            else
                # ── 5. Add new columns to RMP ─────────────────────────
                _add_columns!(rmp, balance, convex, z_vars, cols_p, cols_c, new_p, new_c)
            end
        end

        push!(time_vector, it_time + time_vector[end])
        done && break
        iter += 1
    end

    x_best = iterates[end]
    return x_best, iterates, fun_iterates, time_vector
end
